import React from "react";

export default function Stack() {
  return (
    <>
      <img
        src="https://img.shields.io/badge/Docusaurus-3ECC5F?style=for-the-badge&logo=docusaurus&logoColor=black"
        alt="독사우르스"
        loading="lazy"
        decoding="async"
      />
      <img
        src="https://img.shields.io/badge/React-61DAFB?style=for-the-badge&logo=react&logoColor=black"
        alt="React"
        loading="lazy"
        decoding="async"
      />
      <img
        src="https://img.shields.io/badge/Vercel-181717?style=for-the-badge&logo=vercel&logoColor=white"
        alt="Vercel"
        loading="lazy"
        decoding="async"
      />
      <br />
      <img
        src="https://img.shields.io/badge/visual_studio_code-007ACC?style=for-the-badge&logo=visual-studio&logoColor=white"
        alt="visual_studio_code"
        loading="lazy"
        decoding="async"
      />
      <img
        src="https://img.shields.io/badge/git-F05032?style=for-the-badge&logo=git&logoColor=white"
        alt="git"
        loading="lazy"
        decoding="async"
      />
      <img
        src="https://img.shields.io/badge/npm-CB3837?style=for-the-badge&logo=npm&logoColor=white"
        alt="npm"
        loading="lazy"
        decoding="async"
      />
      <img
        src="https://img.shields.io/badge/github-181717?style=for-the-badge&logo=github&logoColor=white"
        alt="github"
        loading="lazy"
        decoding="async"
      />
      <img
        src="https://img.shields.io/badge/github_actions-%232671E5.svg?style=for-the-badge&logo=github-actions&logoColor=white"
        alt="github_actions"
        loading="lazy"
        decoding="async"
      />
      <img
        src="https://img.shields.io/badge/notion-000000?style=for-the-badge&logo=notion&logoColor=white"
        alt="notion"
        loading="lazy"
        decoding="async"
      />
    </>
  );
}
